version: '3.9'

services:
  postgres:
    image: postgres:alpine
    env_file:
      - ./backend-rest/.env 
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data 

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - database_redis:/data

  backend-rest:
    build: .
    image: backend-rest
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - .:/go/src/app
    command: reflex -r "\.go$$" -s -- sh -c "go run ./"
    depends_on:
      - postgres
      - redis

volumes:
  database_postgres:
  database_redis:

  
